### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by AndrianBdn** [a3linux/go-aws-mon#5]
Hi, 

Thank for for creating and sharing go-aws-mon. 

Can you please add a license to this project? You can do this within github, just create file with LICENSE name and selector will appear automatically. 

I would like to produce derivate work and it would great to know the licensing terms. You can choose the license within few minutes using http://choosealicense.com

**Comment by vanga** [comment]
If you are on a container based OS, its better to use a container built with typical perl/python mon scripts IMO rather than trying to modify these scripts.

I used this for a while, but this lacks some options that perl/python scripts offer, now I use a container to collect metrics.

**Comment by AndrianBdn** [comment]
Thank you for sharing your experience @vanga . I still think that single static executable is better than container. I've already modified the project to my needs (by replacing almost all configuration options with defaults that make sense for me and making it systemd service without cron or timers). 

I will share my results as soon as @a3linux will specify the license.

**Comment by vanga** [comment]
Just another observation that I want to make, based on my exp starting/stopping this monitoring container is very light, I must say I didn't see any difference in the script run time when I migrated from running these go scripts. Before testing I expected starting, stopping container every minute can be heavy and slow.

**Comment by a3linux** [comment]
I put GPLv3 License.
