### ISSUE TITLE
Make the tool dockerise 

### ISSUE THREAD

**Issue by a3linux** [a3linux/go-aws-mon#8]
In my experience, I already used some dockerise script task on CoreOS as install tools on such OS is always hard. 
It will be good if go-aws-mon comes with Docker support by default.

**Comment by ajbeach2** [comment]
Maybe as an alliterative, use docker to cross compile binaries.

**Comment by a3linux** [comment]
I already release the docker image a3linux/aws-go-mon on Docker.io. You can try.

**Comment by a3linux** [comment]
https://github.com/a3linux/go-aws-mon/commit/45a787ca181a4e4d6fb9380e5a8ae8937a3582bf 
Commit to resolve this.
